#!/usr/bin/env python3
"""
Citation reference table — core engine. Hard-coded, deterministic.

Two modes:
  python cite_table.py draft.txt              → body order table only
  python cite_table.py draft.txt --bib refs.bib → 4-column comparison table

All output is bilingual (中文/English auto-detected from draft language).
"""

import re
import sys
import os
import json
from collections import OrderedDict

# Ensure Unicode output on Windows (avoids GBK encoding crash)
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

# Canonical pattern — the LLM normalizes all formats to [CITE:key] before running this
PLACEHOLDER_RE = re.compile(r'\[CITE:([a-zA-Z0-9_\-]+)\]')

# BibTeX entry pattern
BIB_ENTRY_RE = re.compile(r'@(\w+)\{([^,]+),')

DISCLAIMER_EN = (
    'This table was generated by a hard-coded script (cite_table.py). '
    'No LLM involvement — all citations trace back to real placeholders '
    'in the source text.'
)
DISCLAIMER_ZH = (
    '此表由硬编码脚本 (cite_table.py) 生成，无 LLM 参与 — '
    '所有引用均可追溯至源文本中的真实占位符。'
)


def detect_language(text):
    clean = [c for c in text if not c.isspace()]
    if not clean:
        return 'en'
    cjk = sum(1 for c in clean if '一' <= c <= '鿿' or '　' <= c <= '〿')
    return 'zh' if cjk / len(clean) > 0.05 else 'en'


def parse_bib_file(path):
    """Parse a BibTeX file, return OrderedDict of key → (type, label, position)."""
    entries = OrderedDict()
    if not os.path.exists(path):
        return entries
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
    pos = 1
    for m in BIB_ENTRY_RE.finditer(content):
        entry_type = m.group(1)
        key = m.group(2).strip()
        # Try to extract author and year from the entry text
        entries[key] = {
            'type': entry_type,
            'position': pos,
        }
        pos += 1
    return entries


def find_all_citations(text):
    """Find all [CITE:key] placeholders with positions."""
    seen = set()
    matches = []
    for m in PLACEHOLDER_RE.finditer(text):
        key = m.group(1)
        pos = (m.start(), m.end(), key)
        if pos in seen:
            continue
        seen.add(pos)
        matches.append({
            'key': key,
            'start': m.start(),
            'end': m.end(),
            'full': m.group(0),
        })
    matches.sort(key=lambda x: x['start'])
    return matches


def build_mapping(matches):
    seen = OrderedDict()
    for m in matches:
        key = m['key']
        if key not in seen:
            seen[key] = len(seen) + 1
    return seen


def extract_context(text, start, end, half=20):
    before = text[:start].replace('\n', ' ')
    after = text[end:].replace('\n', ' ')
    pre = before[-half:] if len(before) > half else before
    post = after[:half] if len(after) > half else after
    if len(before) > half:
        pre = '...' + pre
    if len(after) > half:
        post = post + '...'
    return pre + '[N]' + post


def check_position(text, start, end, num):
    before = text[:start].rstrip()
    after = text[end:].lstrip()
    # Comma sandwich
    if (before.endswith(',') or before.endswith(', ')) and \
       (after.startswith(',') or after.startswith(', ') or after.startswith('.') or after.startswith(';')):
        if before.rstrip().endswith(','):
            before_words = before.rstrip()[:-1].strip()
            if before_words and not before_words[-1].isdigit():
                return 'sandwich'
    # Author-attached
    before_word = before.split()[-1] if before.split() else ''
    if before_word and before_word[0].isupper() and len(before_word) > 1:
        after_word = after.split()[0] if after.split() else ''
        if after_word and after_word[0].islower() and after_word not in ('and', 'or', 'et', 'al.', 'al'):
            return 'author'
    return 'ok'


def format_author(key, bib_entries=None):
    """Extract author from bib entry if available, otherwise from cite key."""
    if bib_entries and key in bib_entries:
        # Try to extract author from bib entry text
        pass  # bib entry parsing would need full BibTeX field extraction
    name = re.split(r'\d', key)[0]
    if not name:
        return key
    # Handle keys like 'ref19' → 'Ref 19', 'smith2023' → 'Smith'
    if name.lower() in ('ref', 'cite', 'bib', 'fn', 'note'):
        return f'{name.capitalize()} {key[len(name):]}'
    if name[0].islower():
        name = name[0].upper() + name[1:]
    return name


def format_bib_label(entry):
    """Short label for bib entry."""
    t = entry['type']
    short = {'article': 'art', 'inproceedings': 'conf', 'book': 'book',
             'incollection': 'chap', 'phdthesis': 'phd', 'mastersthesis': 'msc'}
    return short.get(t, t[:4])


def main():
    draft_file = None
    bib_file = None

    args = [a for a in sys.argv[1:] if not a.startswith('--help') and a != '-h']
    if '--bib' in sys.argv:
        idx = sys.argv.index('--bib')
        if idx + 1 < len(sys.argv):
            bib_file = sys.argv[idx + 1]
        if len(args) > 0 and args[0] == sys.argv[idx]:
            args.pop(0)
        if idx < len(sys.argv):
            args = [a for a in args if a != sys.argv[idx]]

    if len(args) > 0:
        draft_file = args[0]
        with open(draft_file, 'r', encoding='utf-8') as f:
            text = f.read()
    else:
        text = sys.stdin.read()

    lang = detect_language(text)
    zh = lang == 'zh'

    disclaimer = DISCLAIMER_ZH if zh else DISCLAIMER_EN
    num_hdr = '序号' if zh else '#'
    author_hdr = '作者' if zh else 'Author'
    ctx_hdr = '正文引用(前后20字)' if zh else 'Body Context (40)'
    ref_hdr = '参考文献' if zh else 'Reference'
    status_hdr = '状态' if zh else 'Status'

    # Parse bib if provided
    bib_entries = {}
    if bib_file:
        bib_entries = parse_bib_file(bib_file)

    matches = find_all_citations(text)
    mapping = build_mapping(matches)

    # Build occurrences
    occurrences = []
    for m in matches:
        key = m['key']
        num = mapping[key]
        ctx = extract_context(text, m['start'], m['end'])
        ctx = ctx.replace('[N]', f'[{num}]')
        pos_status = check_position(text, m['start'], m['end'], num)
        occurrences.append({
            'num': num,
            'key': key,
            'context': ctx,
            'pos_status': pos_status,
        })

    # First/sub rows
    key_seen = {}
    warnings = {'sandwich': 0, 'author': 0}
    for occ in occurrences:
        key = occ['key']
        if key not in key_seen:
            key_seen[key] = 1
            occ['row_type'] = 'first'
            occ['status'] = occ['pos_status']
            if 'sandwich' in occ['pos_status']:
                warnings['sandwich'] += 1
            if 'author' in occ['pos_status']:
                warnings['author'] += 1
        else:
            occ['row_type'] = 'sub'
            occ['status'] = 'ok'

    # Build output
    lines = ['']
    lines.append(disclaimer)
    lines.append('')

    if bib_file and bib_entries:
        # === 4-COLUMN COMPARISON TABLE ===
        bib_key_hdr = 'Bib Key' if zh else 'Bib Key'
        bib_pos_hdr = 'Bib文件位' if zh else 'Bib Pos'
        ref_order_hdr = '参考文献序' if zh else 'Ref Order'
        status_col_hdr = '状态' if zh else 'Status'

        w_num = 6
        w_author = 12
        w_bibkey = 18
        w_bibpos = 8
        w_reforder = 8
        w_status = 14
        total_w = w_num + w_author + w_bibkey + w_bibpos + w_reforder + w_status + 6

        title = '引用顺序对照表' if zh else 'Citation Order Comparison'
        lines.append(f'{title}')
        lines.append('')
        lines.append(
            f'{num_hdr:<{w_num}}  '
            f'{author_hdr:<{w_author}}  '
            f'{bib_key_hdr:<{w_bibkey}}  '
            f'{bib_pos_hdr:<{w_bibpos}}  '
            f'{ref_order_hdr:<{w_reforder}}  '
            f'{status_col_hdr:<{w_status}}'
        )
        lines.append('-' * total_w)

        bib_mismatches = 0
        seen_keys = set()
        for occ in occurrences:
            key = occ['key']
            if key in seen_keys:
                continue
            seen_keys.add(key)
            author = format_author(key, bib_entries)
            num = occ['num']

            bib_info = bib_entries.get(key)
            bib_pos_str = f'#{bib_info["position"]}' if bib_info else '—'
            bib_key_str = key

            # Status: check if bib key naming matches body order
            # Convention: key like ref01 should map to [1], ref02 to [2]
            digits = re.findall(r'\d+', key)
            if digits:
                key_num = int(digits[-1])
                expected_key_num = num
                if key_num != expected_key_num:
                    status = '⚠️ 编号不匹配' if zh else '⚠️ mismatch'
                    bib_mismatches += 1
                else:
                    status = '✅' if zh else '✅'
            else:
                status = '✅' if zh else '✅'

            ref_order_str = f'[{num}]'

            lines.append(
                f'[{num}]' + ' ' * (w_num - 3) + '  '
                f'{author:<{w_author}}  '
                f'{bib_key_str:<{w_bibkey}}  '
                f'{bib_pos_str:<{w_bibpos}}  '
                f'{ref_order_str:<{w_reforder}}  '
                f'{status:<{w_status}}'
            )

        lines.append('-' * total_w)
        total_str = f'{len(key_seen)} refs compared.' if not zh else f'共对比 {len(key_seen)} 篇参考文献。'
        if bib_mismatches > 0:
            lines.append(total_str)
            note = (f'  {bib_mismatches} bib key(s) do not match body citation order. '
                    f'Consider renaming keys to match.')
            zh_note = (f'  {bib_mismatches} 个 Bib Key 与正文引用顺序不一致，建议重命名以匹配编号。')
            lines.append(zh_note if zh else note)
        else:
            lines.append(total_str)
            ok_note = '  All bib keys match body citation order.' if not zh else '  所有 Bib Key 与正文引用顺序一致。'
            lines.append(ok_note)

    else:
        # === 5-COLUMN BODY ORDER TABLE (no bib) ===
        w_num = 6
        w_author = 10
        w_ctx = 42
        w_ref = 28
        w_status = 10
        total_w = w_num + w_author + w_ctx + w_ref + w_status + 4

        lines.append(
            f'{num_hdr:<{w_num}} '
            f'{author_hdr:<{w_author}} '
            f'{ctx_hdr:<{w_ctx}} '
            f'{ref_hdr:<{w_ref}} '
            f'{status_hdr:<{w_status}}'
        )
        lines.append('-' * total_w)

        for occ in occurrences:
            num = occ['num']
            key = occ['key']
            author = format_author(key)

            ref_label = f'[{num}] {author}'
            status_display = '✅' if occ['status'] == 'ok' else f'⚠️{occ["status"]}'

            if occ['row_type'] == 'first':
                lines.append(
                    f'[{num}]{" "*(w_num-3)} '
                    f'{author:<{w_author}} '
                    f'{occ["context"]:<{w_ctx}} '
                    f'{ref_label:<{w_ref}} '
                    f'{status_display:<{w_status}}'
                )
            else:
                lines.append(
                    f'     ↳{" "*(w_num-4)} '
                    f'{"↳":<{w_author}} '
                    f'{occ["context"]:<{w_ctx}} '
                    f'{"↳":<{w_ref}} '
                    f'{status_display:<{w_status}}'
                )

        lines.append('-' * total_w)
        lines.append(f'{len(key_seen)} refs, {len(occurrences)} occurrences.' if not zh
                     else f'{len(key_seen)} 篇, {len(occurrences)} 处引用.')

    # Position warnings (for body-only mode)
    if not bib_file and (warnings['sandwich'] > 0 or warnings['author'] > 0):
        lines.append('')
        lines.append('引用位置警告:' if zh else 'Placement warnings:')
        if warnings['sandwich'] > 0:
            en = f'  {warnings["sandwich"]} comma-sandwich citation(s) marked ⚠️sandwich'
            zh_str = f'  {warnings["sandwich"]} 处逗号夹心引用，已标记 ⚠️sandwich'
            lines.append(zh_str if zh else en)
        if warnings['author'] > 0:
            en = f'  {warnings["author"]} author-attached citation(s) marked ⚠️author'
            zh_str = f'  {warnings["author"]} 处作者附着引用，已标记 ⚠️author'
            lines.append(zh_str if zh else en)
        fix_en = '  Fix: move citations to sentence-end or natural pause.'
        fix_zh = '  修复：将引用移至句末或自然停顿处。'
        lines.append(fix_zh if zh else fix_en)

    output = '\n'.join(lines)
    print(output)

    out_file = os.path.join(os.path.dirname(__file__), 'cite_output.txt')
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(output)


if __name__ == '__main__':
    main()
